//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Assets/Scripts/InputSystem/GeneratedScript/MainControllsAcrossPlatforms.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainControllsAcrossPlatforms : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainControllsAcrossPlatforms()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainControllsAcrossPlatforms"",
    ""maps"": [
        {
            ""name"": ""DialogueControllsKit"",
            ""id"": ""24f4bb75-3561-4ddc-89a0-349e364e43c7"",
            ""actions"": [
                {
                    ""name"": ""SelectionKey"",
                    ""type"": ""Button"",
                    ""id"": ""cb9435f1-c8c5-42ec-827e-fd0484bd6a92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDialogueRight"",
                    ""type"": ""Button"",
                    ""id"": ""d9e9c5e3-f6d1-4167-af98-b8ec1ee02f26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDialogueLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1539ae42-b202-46ae-936a-2c096279a65d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc467b54-07f4-458c-add2-b4e3105c8df4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5ea5db2-6a56-46b1-b758-821dc95c0e8a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c3d66ab-6ff1-45c5-a241-36c889464ac6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04c6182f-725f-4f38-b023-b07e96927472"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e565965-437e-46ff-abee-93509369276a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd521545-026f-4144-8623-52f42fc9dd87"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1bf838b-9cc4-400d-8f09-1e0293f7656a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f50826a-b673-4758-b000-79475250caa3"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db08e342-ddce-4d96-84d5-535f8c50fdf1"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffa4db28-e3e9-466e-92d0-e9589636d842"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f30e490e-4332-4e6e-bc04-595e5825655c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77c76bac-f6d4-4622-9a9a-9ef2b8aacdf5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24a95c04-a70a-4f5c-b0d9-44849ab83d32"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d198a582-9a6f-4334-97cf-7a3c831ff96a"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87121f5b-3b5c-4334-ad68-e332337ff53f"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDialogueLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MovementAndInteractionsKit"",
            ""id"": ""bf224df9-c457-46c9-a7f1-08e2d2f47031"",
            ""actions"": [
                {
                    ""name"": ""MovementX"",
                    ""type"": ""Button"",
                    ""id"": ""b1571bab-8a14-4f0d-8644-21bb0e41eafe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementZ"",
                    ""type"": ""Button"",
                    ""id"": ""21b857fe-c5a4-4232-b277-6d381b173eed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractionKey"",
                    ""type"": ""Button"",
                    ""id"": ""01ffe7f7-b1ac-49f4-b0ed-350fce559546"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpKey"",
                    ""type"": ""Button"",
                    ""id"": ""0136fddb-c950-4d89-8276-88c9b5eaa35e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""MovementPC "",
                    ""id"": ""48e293d4-9ed8-461d-81d9-5e07485e3dd2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d9744672-25be-4344-91fa-c93c9e7a88cd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9e436b29-26f9-4819-b70f-01fbed11283f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1179af59-fb2b-4344-b7a6-93ecf89757e5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""65cbb494-ee7d-4d7a-b06b-4a03ba5c2b4b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8e6f345a-8de4-4e04-a037-8fd5f63f0c01"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b1f234f-d8a7-47bc-8cdc-2ad77c07e44f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcf149fe-f687-4b44-9b58-328598c6b625"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6c7508c-2533-4c64-974c-46e485df8aea"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c07b11e-8fff-4e75-bf8b-3380a6c3d0c2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b25875f8-dbaf-45f8-ab5e-8f91d1ac6dc4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbc4053e-46e3-45a0-8404-a5089c016fbc"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15a8d731-a7a6-4150-b94e-e3cccde5a641"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MovementGamepad"",
                    ""id"": ""cbfa08fe-b069-42d9-a9a0-f80d7de88e44"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cda4762e-2ce0-4e17-89a1-c950d31313a2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""df109408-fc69-4094-a552-c10d0c26392e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""de45c9e0-8cbd-4a22-9da2-051492da7c95"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7c361ec5-54d2-4b73-ba4d-b495dab35fc2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MovementPC "",
                    ""id"": ""beb17761-c089-49cb-9517-53f461ceaab0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""048f073f-0e0e-44a5-b50e-28d53b8c043d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""de78b405-849c-437d-8764-3a4d7b309baf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6f2c862f-baa5-4ec5-a392-f9d97ba8392a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dde4bf1a-4ef2-4462-8d6e-543532a37f5e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""MovementGamepad"",
                    ""id"": ""3bc9a35f-1748-475b-ae36-560c06cb076f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""37840f12-51f6-4e24-8520-6077bc6a9fda"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""395d5a60-a6b7-453d-8402-8d83c45b25a6"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fc40b811-f248-4a17-9ac4-c782a5fd2445"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b836cd93-2578-4cd4-80d7-71d82569f275"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""DialogueOnlyPlayerKit"",
            ""id"": ""11525a0c-35c4-462e-ab25-8958ddf5e88f"",
            ""actions"": [
                {
                    ""name"": ""SelectionKeyPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""739c7469-0108-4e5a-8166-df8c55aceaef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b40a2db4-744a-4bd9-abf0-686a64df830e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1d845d1-7124-45d0-a7d7-0711905ceb34"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c873b6da-c581-4910-a23c-b77dc327f30f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DialogueOnlyNpcKit"",
            ""id"": ""ebb5d97a-f43e-4267-8f56-6a10929a730a"",
            ""actions"": [
                {
                    ""name"": ""SelectionKeyNpc"",
                    ""type"": ""Button"",
                    ""id"": ""8c988312-28b2-40cd-bdbf-423b36f054a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8b3d9d27-30fe-4c4c-86fb-f66bd3fab484"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyNpc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff7e8127-4c9d-4dba-b80d-5abb8f8da797"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyNpc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9a64fb2-31b1-42b9-9d9b-79a9c3e694e8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""SelectionKeyNpc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DrumKit"",
            ""id"": ""b9d35c14-983f-45dd-b4a5-1b378ef5fd6e"",
            ""actions"": [
                {
                    ""name"": ""UpDrum"",
                    ""type"": ""Button"",
                    ""id"": ""eb99abff-0ec3-4da1-82fa-36e77b739f43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownDrum"",
                    ""type"": ""Button"",
                    ""id"": ""f739656f-876d-464c-be76-9f631e737332"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDrum"",
                    ""type"": ""Button"",
                    ""id"": ""08197085-f720-469a-8f4d-80a636c4f4a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDrum"",
                    ""type"": ""Button"",
                    ""id"": ""e8593c44-f594-456d-b139-bcd4478bff7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe48ff9f-43d3-4998-82f9-ea12c2f19f37"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e309cbdc-7898-49ad-b2f7-3399436cf589"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fed38cb-11da-4806-b1c2-e3c9d5ea0b15"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b9ef0d9-1649-41bb-afb2-56aa22480db4"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29850248-1319-4240-a1fa-be64b1e40988"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""067dd88f-b42f-484f-888a-cc89e78435ba"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f8cceda-cc7a-4600-8bf6-73e50ecc54c0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cbab419-a7f8-4ae1-a972-d7a88bf14e2b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e0ae1fd-e7c5-4568-8217-dd7ae2099b2c"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e00d3d6-e311-407c-8022-49acc9dcdbde"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e2952eb-d211-4297-86ed-2914054678fa"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e1aee96-d6b9-4a9b-8097-18a8e43c0ec0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e3c3557-eda2-4cf9-ae58-a7f7ad1fc4a7"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bbd9267-ae86-424d-ab71-6b820dd80bdf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""910d3bbf-123e-4ed1-a1b3-a7d9a461c5fe"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad61ee00-8e83-408d-94c3-3130be33293f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f21f388-a2a7-44c6-ace0-22da26b1a479"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e105852f-793f-4341-b5ce-042106ca8bf5"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e5128ed-8877-4c9f-ba35-da0d01a6169e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa3e4134-38b1-4aae-b806-20c9a84fa1f7"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDrum"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main"",
            ""bindingGroup"": ""Main"",
            ""devices"": [
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<SwitchProControllerHID>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // DialogueControllsKit
        m_DialogueControllsKit = asset.FindActionMap("DialogueControllsKit", throwIfNotFound: true);
        m_DialogueControllsKit_SelectionKey = m_DialogueControllsKit.FindAction("SelectionKey", throwIfNotFound: true);
        m_DialogueControllsKit_ChangeDialogueRight = m_DialogueControllsKit.FindAction("ChangeDialogueRight", throwIfNotFound: true);
        m_DialogueControllsKit_ChangeDialogueLeft = m_DialogueControllsKit.FindAction("ChangeDialogueLeft", throwIfNotFound: true);
        // MovementAndInteractionsKit
        m_MovementAndInteractionsKit = asset.FindActionMap("MovementAndInteractionsKit", throwIfNotFound: true);
        m_MovementAndInteractionsKit_MovementX = m_MovementAndInteractionsKit.FindAction("MovementX", throwIfNotFound: true);
        m_MovementAndInteractionsKit_MovementZ = m_MovementAndInteractionsKit.FindAction("MovementZ", throwIfNotFound: true);
        m_MovementAndInteractionsKit_InteractionKey = m_MovementAndInteractionsKit.FindAction("InteractionKey", throwIfNotFound: true);
        m_MovementAndInteractionsKit_JumpKey = m_MovementAndInteractionsKit.FindAction("JumpKey", throwIfNotFound: true);
        // DialogueOnlyPlayerKit
        m_DialogueOnlyPlayerKit = asset.FindActionMap("DialogueOnlyPlayerKit", throwIfNotFound: true);
        m_DialogueOnlyPlayerKit_SelectionKeyPlayer = m_DialogueOnlyPlayerKit.FindAction("SelectionKeyPlayer", throwIfNotFound: true);
        // DialogueOnlyNpcKit
        m_DialogueOnlyNpcKit = asset.FindActionMap("DialogueOnlyNpcKit", throwIfNotFound: true);
        m_DialogueOnlyNpcKit_SelectionKeyNpc = m_DialogueOnlyNpcKit.FindAction("SelectionKeyNpc", throwIfNotFound: true);
        // DrumKit
        m_DrumKit = asset.FindActionMap("DrumKit", throwIfNotFound: true);
        m_DrumKit_UpDrum = m_DrumKit.FindAction("UpDrum", throwIfNotFound: true);
        m_DrumKit_DownDrum = m_DrumKit.FindAction("DownDrum", throwIfNotFound: true);
        m_DrumKit_LeftDrum = m_DrumKit.FindAction("LeftDrum", throwIfNotFound: true);
        m_DrumKit_RightDrum = m_DrumKit.FindAction("RightDrum", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DialogueControllsKit
    private readonly InputActionMap m_DialogueControllsKit;
    private IDialogueControllsKitActions m_DialogueControllsKitActionsCallbackInterface;
    private readonly InputAction m_DialogueControllsKit_SelectionKey;
    private readonly InputAction m_DialogueControllsKit_ChangeDialogueRight;
    private readonly InputAction m_DialogueControllsKit_ChangeDialogueLeft;
    public struct DialogueControllsKitActions
    {
        private @MainControllsAcrossPlatforms m_Wrapper;
        public DialogueControllsKitActions(@MainControllsAcrossPlatforms wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectionKey => m_Wrapper.m_DialogueControllsKit_SelectionKey;
        public InputAction @ChangeDialogueRight => m_Wrapper.m_DialogueControllsKit_ChangeDialogueRight;
        public InputAction @ChangeDialogueLeft => m_Wrapper.m_DialogueControllsKit_ChangeDialogueLeft;
        public InputActionMap Get() { return m_Wrapper.m_DialogueControllsKit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueControllsKitActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueControllsKitActions instance)
        {
            if (m_Wrapper.m_DialogueControllsKitActionsCallbackInterface != null)
            {
                @SelectionKey.started -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnSelectionKey;
                @SelectionKey.performed -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnSelectionKey;
                @SelectionKey.canceled -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnSelectionKey;
                @ChangeDialogueRight.started -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueRight;
                @ChangeDialogueRight.performed -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueRight;
                @ChangeDialogueRight.canceled -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueRight;
                @ChangeDialogueLeft.started -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueLeft;
                @ChangeDialogueLeft.performed -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueLeft;
                @ChangeDialogueLeft.canceled -= m_Wrapper.m_DialogueControllsKitActionsCallbackInterface.OnChangeDialogueLeft;
            }
            m_Wrapper.m_DialogueControllsKitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectionKey.started += instance.OnSelectionKey;
                @SelectionKey.performed += instance.OnSelectionKey;
                @SelectionKey.canceled += instance.OnSelectionKey;
                @ChangeDialogueRight.started += instance.OnChangeDialogueRight;
                @ChangeDialogueRight.performed += instance.OnChangeDialogueRight;
                @ChangeDialogueRight.canceled += instance.OnChangeDialogueRight;
                @ChangeDialogueLeft.started += instance.OnChangeDialogueLeft;
                @ChangeDialogueLeft.performed += instance.OnChangeDialogueLeft;
                @ChangeDialogueLeft.canceled += instance.OnChangeDialogueLeft;
            }
        }
    }
    public DialogueControllsKitActions @DialogueControllsKit => new DialogueControllsKitActions(this);

    // MovementAndInteractionsKit
    private readonly InputActionMap m_MovementAndInteractionsKit;
    private IMovementAndInteractionsKitActions m_MovementAndInteractionsKitActionsCallbackInterface;
    private readonly InputAction m_MovementAndInteractionsKit_MovementX;
    private readonly InputAction m_MovementAndInteractionsKit_MovementZ;
    private readonly InputAction m_MovementAndInteractionsKit_InteractionKey;
    private readonly InputAction m_MovementAndInteractionsKit_JumpKey;
    public struct MovementAndInteractionsKitActions
    {
        private @MainControllsAcrossPlatforms m_Wrapper;
        public MovementAndInteractionsKitActions(@MainControllsAcrossPlatforms wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementX => m_Wrapper.m_MovementAndInteractionsKit_MovementX;
        public InputAction @MovementZ => m_Wrapper.m_MovementAndInteractionsKit_MovementZ;
        public InputAction @InteractionKey => m_Wrapper.m_MovementAndInteractionsKit_InteractionKey;
        public InputAction @JumpKey => m_Wrapper.m_MovementAndInteractionsKit_JumpKey;
        public InputActionMap Get() { return m_Wrapper.m_MovementAndInteractionsKit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementAndInteractionsKitActions set) { return set.Get(); }
        public void SetCallbacks(IMovementAndInteractionsKitActions instance)
        {
            if (m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface != null)
            {
                @MovementX.started -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementX;
                @MovementX.performed -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementX;
                @MovementX.canceled -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementX;
                @MovementZ.started -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementZ;
                @MovementZ.performed -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementZ;
                @MovementZ.canceled -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnMovementZ;
                @InteractionKey.started -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnInteractionKey;
                @InteractionKey.performed -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnInteractionKey;
                @InteractionKey.canceled -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnInteractionKey;
                @JumpKey.started -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnJumpKey;
                @JumpKey.performed -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnJumpKey;
                @JumpKey.canceled -= m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface.OnJumpKey;
            }
            m_Wrapper.m_MovementAndInteractionsKitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovementX.started += instance.OnMovementX;
                @MovementX.performed += instance.OnMovementX;
                @MovementX.canceled += instance.OnMovementX;
                @MovementZ.started += instance.OnMovementZ;
                @MovementZ.performed += instance.OnMovementZ;
                @MovementZ.canceled += instance.OnMovementZ;
                @InteractionKey.started += instance.OnInteractionKey;
                @InteractionKey.performed += instance.OnInteractionKey;
                @InteractionKey.canceled += instance.OnInteractionKey;
                @JumpKey.started += instance.OnJumpKey;
                @JumpKey.performed += instance.OnJumpKey;
                @JumpKey.canceled += instance.OnJumpKey;
            }
        }
    }
    public MovementAndInteractionsKitActions @MovementAndInteractionsKit => new MovementAndInteractionsKitActions(this);

    // DialogueOnlyPlayerKit
    private readonly InputActionMap m_DialogueOnlyPlayerKit;
    private IDialogueOnlyPlayerKitActions m_DialogueOnlyPlayerKitActionsCallbackInterface;
    private readonly InputAction m_DialogueOnlyPlayerKit_SelectionKeyPlayer;
    public struct DialogueOnlyPlayerKitActions
    {
        private @MainControllsAcrossPlatforms m_Wrapper;
        public DialogueOnlyPlayerKitActions(@MainControllsAcrossPlatforms wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectionKeyPlayer => m_Wrapper.m_DialogueOnlyPlayerKit_SelectionKeyPlayer;
        public InputActionMap Get() { return m_Wrapper.m_DialogueOnlyPlayerKit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueOnlyPlayerKitActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueOnlyPlayerKitActions instance)
        {
            if (m_Wrapper.m_DialogueOnlyPlayerKitActionsCallbackInterface != null)
            {
                @SelectionKeyPlayer.started -= m_Wrapper.m_DialogueOnlyPlayerKitActionsCallbackInterface.OnSelectionKeyPlayer;
                @SelectionKeyPlayer.performed -= m_Wrapper.m_DialogueOnlyPlayerKitActionsCallbackInterface.OnSelectionKeyPlayer;
                @SelectionKeyPlayer.canceled -= m_Wrapper.m_DialogueOnlyPlayerKitActionsCallbackInterface.OnSelectionKeyPlayer;
            }
            m_Wrapper.m_DialogueOnlyPlayerKitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectionKeyPlayer.started += instance.OnSelectionKeyPlayer;
                @SelectionKeyPlayer.performed += instance.OnSelectionKeyPlayer;
                @SelectionKeyPlayer.canceled += instance.OnSelectionKeyPlayer;
            }
        }
    }
    public DialogueOnlyPlayerKitActions @DialogueOnlyPlayerKit => new DialogueOnlyPlayerKitActions(this);

    // DialogueOnlyNpcKit
    private readonly InputActionMap m_DialogueOnlyNpcKit;
    private IDialogueOnlyNpcKitActions m_DialogueOnlyNpcKitActionsCallbackInterface;
    private readonly InputAction m_DialogueOnlyNpcKit_SelectionKeyNpc;
    public struct DialogueOnlyNpcKitActions
    {
        private @MainControllsAcrossPlatforms m_Wrapper;
        public DialogueOnlyNpcKitActions(@MainControllsAcrossPlatforms wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectionKeyNpc => m_Wrapper.m_DialogueOnlyNpcKit_SelectionKeyNpc;
        public InputActionMap Get() { return m_Wrapper.m_DialogueOnlyNpcKit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueOnlyNpcKitActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueOnlyNpcKitActions instance)
        {
            if (m_Wrapper.m_DialogueOnlyNpcKitActionsCallbackInterface != null)
            {
                @SelectionKeyNpc.started -= m_Wrapper.m_DialogueOnlyNpcKitActionsCallbackInterface.OnSelectionKeyNpc;
                @SelectionKeyNpc.performed -= m_Wrapper.m_DialogueOnlyNpcKitActionsCallbackInterface.OnSelectionKeyNpc;
                @SelectionKeyNpc.canceled -= m_Wrapper.m_DialogueOnlyNpcKitActionsCallbackInterface.OnSelectionKeyNpc;
            }
            m_Wrapper.m_DialogueOnlyNpcKitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectionKeyNpc.started += instance.OnSelectionKeyNpc;
                @SelectionKeyNpc.performed += instance.OnSelectionKeyNpc;
                @SelectionKeyNpc.canceled += instance.OnSelectionKeyNpc;
            }
        }
    }
    public DialogueOnlyNpcKitActions @DialogueOnlyNpcKit => new DialogueOnlyNpcKitActions(this);

    // DrumKit
    private readonly InputActionMap m_DrumKit;
    private IDrumKitActions m_DrumKitActionsCallbackInterface;
    private readonly InputAction m_DrumKit_UpDrum;
    private readonly InputAction m_DrumKit_DownDrum;
    private readonly InputAction m_DrumKit_LeftDrum;
    private readonly InputAction m_DrumKit_RightDrum;
    public struct DrumKitActions
    {
        private @MainControllsAcrossPlatforms m_Wrapper;
        public DrumKitActions(@MainControllsAcrossPlatforms wrapper) { m_Wrapper = wrapper; }
        public InputAction @UpDrum => m_Wrapper.m_DrumKit_UpDrum;
        public InputAction @DownDrum => m_Wrapper.m_DrumKit_DownDrum;
        public InputAction @LeftDrum => m_Wrapper.m_DrumKit_LeftDrum;
        public InputAction @RightDrum => m_Wrapper.m_DrumKit_RightDrum;
        public InputActionMap Get() { return m_Wrapper.m_DrumKit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DrumKitActions set) { return set.Get(); }
        public void SetCallbacks(IDrumKitActions instance)
        {
            if (m_Wrapper.m_DrumKitActionsCallbackInterface != null)
            {
                @UpDrum.started -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnUpDrum;
                @UpDrum.performed -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnUpDrum;
                @UpDrum.canceled -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnUpDrum;
                @DownDrum.started -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnDownDrum;
                @DownDrum.performed -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnDownDrum;
                @DownDrum.canceled -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnDownDrum;
                @LeftDrum.started -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnLeftDrum;
                @LeftDrum.performed -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnLeftDrum;
                @LeftDrum.canceled -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnLeftDrum;
                @RightDrum.started -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnRightDrum;
                @RightDrum.performed -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnRightDrum;
                @RightDrum.canceled -= m_Wrapper.m_DrumKitActionsCallbackInterface.OnRightDrum;
            }
            m_Wrapper.m_DrumKitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UpDrum.started += instance.OnUpDrum;
                @UpDrum.performed += instance.OnUpDrum;
                @UpDrum.canceled += instance.OnUpDrum;
                @DownDrum.started += instance.OnDownDrum;
                @DownDrum.performed += instance.OnDownDrum;
                @DownDrum.canceled += instance.OnDownDrum;
                @LeftDrum.started += instance.OnLeftDrum;
                @LeftDrum.performed += instance.OnLeftDrum;
                @LeftDrum.canceled += instance.OnLeftDrum;
                @RightDrum.started += instance.OnRightDrum;
                @RightDrum.performed += instance.OnRightDrum;
                @RightDrum.canceled += instance.OnRightDrum;
            }
        }
    }
    public DrumKitActions @DrumKit => new DrumKitActions(this);
    private int m_MainSchemeIndex = -1;
    public InputControlScheme MainScheme
    {
        get
        {
            if (m_MainSchemeIndex == -1) m_MainSchemeIndex = asset.FindControlSchemeIndex("Main");
            return asset.controlSchemes[m_MainSchemeIndex];
        }
    }
    public interface IDialogueControllsKitActions
    {
        void OnSelectionKey(InputAction.CallbackContext context);
        void OnChangeDialogueRight(InputAction.CallbackContext context);
        void OnChangeDialogueLeft(InputAction.CallbackContext context);
    }
    public interface IMovementAndInteractionsKitActions
    {
        void OnMovementX(InputAction.CallbackContext context);
        void OnMovementZ(InputAction.CallbackContext context);
        void OnInteractionKey(InputAction.CallbackContext context);
        void OnJumpKey(InputAction.CallbackContext context);
    }
    public interface IDialogueOnlyPlayerKitActions
    {
        void OnSelectionKeyPlayer(InputAction.CallbackContext context);
    }
    public interface IDialogueOnlyNpcKitActions
    {
        void OnSelectionKeyNpc(InputAction.CallbackContext context);
    }
    public interface IDrumKitActions
    {
        void OnUpDrum(InputAction.CallbackContext context);
        void OnDownDrum(InputAction.CallbackContext context);
        void OnLeftDrum(InputAction.CallbackContext context);
        void OnRightDrum(InputAction.CallbackContext context);
    }
}
